version: '3.9'
services:
  mysql:
    image: mysql
    container_name: banco-dados
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678987654321
      MYSQL_USER: drzebra
      MYSQL_PASSWORD: 12345678987654321
    volumes:
      - ./Database/dbdata:/var/lib/mysql
    ports:
      - '3002:3306'
  
  gera-estoque:
    image: dz-gera-estoque
    container_name: gera-estoque
    ports:
      - "3001:3001"

  front-end:
    image: dz-front-end
    container_name: front
    ports:
      - "3000:3000"