version: '3.9'
services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    ports: 
      - '3002:3306'


  gera-estoque:
    image: gera-estoque
    container_name: gera-estoque
    ports:
      - "3001:3001"
  
  