/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author luisandres
 */
public class Dados extends javax.swing.JInternalFrame {

    Map<Object, Integer> referenceMap = null;
    Map<Object, Integer> costureiroMap = null;
    String host = "localhost";
    Integer selectedCostureiro = null; 
    Integer selectedReferencia = null;

    /**
     *
     * @param host
     */
    public Dados(String host) {
        this.host = host;
        initComponents();
        alimentaTabela();
    }
    
    /**
     *
     */
    public void alimentaTabela(){
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        selectedCostureiro = null;
        selectedReferencia = null;
        referenceMap = new LinkedHashMap<>();
        costureiroMap = new LinkedHashMap<>();
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        
        String url1 = "http://"+this.host+"/produzido/listaProduzido";
        String url2 = "http://"+this.host+"/produzido/listaProduzidoJunto";
        var result1 = ConnectionFactory.simpleGet(url1);
        var result2 = ConnectionFactory.simpleGet(url2);
        JSONArray jsonArrayProduzidos = new JSONArray(result1);
        JSONArray jsonArrayProduzidosJunto = new JSONArray(result2);
        
        String url3 = "http://"+this.host+"/costureiro/listarCostureiro";
        String url4 = "http://"+this.host+"/produto/getListaProdutosProduzidos";
        var result3 = ConnectionFactory.simpleGet(url3);
        var result4 = ConnectionFactory.simpleGet(url4);    
        JSONArray jsonArrayCostureiros = new JSONArray(result3);
        JSONArray jsonArrayReferencias = new JSONArray(result4);
        
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        modelo1.setNumRows(0);     
        modelo2.setNumRows(0);
        for (int i = 0; i < jsonArrayProduzidos.length(); i++) {
            JSONObject obj = jsonArrayProduzidos.getJSONObject(i);
            modelo1.addRow(new Object[]{
                obj.getString("referencia"),
                obj.getInt("producao_diaria"),
                obj.getString("costureiro"),
                obj.getString("dia")
               });
        }
        
        for (int i = 0; i < jsonArrayProduzidosJunto.length(); i++){
            JSONObject obj = jsonArrayProduzidosJunto.getJSONObject(i);
            modelo2.addRow(new Object[]{
                obj.getString("costureiro"),
                obj.getInt("producao_diaria"),
                obj.getString("dia")
            });
        }
        
        for (int i = 0; i < jsonArrayCostureiros.length(); i++) {
            JSONObject obj = jsonArrayCostureiros.getJSONObject(i);
            int id = obj.getInt("id");
            String nome = obj.getString("nome");
            costureiroMap.put(new Object[]{id, nome}, id);
            jComboBox1.addItem(nome);
        }
        for (int i = 0; i < jsonArrayReferencias.length(); i++) {
            JSONObject obj = jsonArrayReferencias.getJSONObject(i);
            int id = obj.getInt("id_produto");
            String referencia = obj.getString("referencia");
            referenceMap.put(new Object[]{id, referencia}, id);
            jComboBox2.addItem(referencia);
        }
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Dados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Referência", "Qnt.", "Costureiro", "Dia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Costureiro", "Quantia Total", "Dia"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Atualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Costureiro:");

        jLabel2.setText("Referência:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jButton2.setText("Buscar Costureiro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar Ref");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String url1 = "http://"+this.host+"/produzido/listaProduzido?costureiro_id="+selectedCostureiro;
        var result1 = ConnectionFactory.simpleGet(url1);
        JSONArray jsonArrayProduzidos = new JSONArray(result1);
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        modelo1.setNumRows(0);
        for (int i = 0; i < jsonArrayProduzidos.length(); i++) {
            JSONObject obj = jsonArrayProduzidos.getJSONObject(i);
            modelo1.addRow(new Object[]{
                obj.getString("referencia"),
                obj.getInt("producao_diaria"),
                obj.getString("costureiro"),
                obj.getString("dia")
               });
        }
        String url2 = "http://"+this.host+"/produzido/listaProduzidoJunto?costureiro_id="+selectedCostureiro;
        var result2 = ConnectionFactory.simpleGet(url2);
        JSONArray jsonArrayProduzidosJunto = new JSONArray(result2);
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        modelo2.setNumRows(0);
        for (int i = 0; i < jsonArrayProduzidosJunto.length(); i++) {
            JSONObject obj = jsonArrayProduzidosJunto.getJSONObject(i);
            modelo2.addRow(new Object[]{
                obj.getString("costureiro"),
                obj.getInt("producao_diaria"),
                obj.getString("dia")
            });
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String selectedCostureiro = (String) jComboBox1.getSelectedItem();
        if (selectedCostureiro != null){
            Object selected = null;
            for (Object key : costureiroMap.keySet()) {
                Object[] costureiro = (Object[]) key;
                String referencia = (String) costureiro[1];
                if (referencia.equals(selectedCostureiro)) {
                    selected = key;
                    Object[] objeto = (Object[]) selected;
                    this.selectedCostureiro = (int) objeto[0];
                    break;
                }
            }            
        }      
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        String selectedReference = (String) jComboBox2.getSelectedItem();
        if (selectedReference != null){
            Object selected = null;
            for (Object key : referenceMap.keySet()) {
                Object[] reference = (Object[]) key;
                String referencia = (String) reference[1];
                if (referencia.equals(selectedReference)) {
                    selected = key;
                    Object[] objeto = (Object[]) selected;
                    this.selectedReferencia = (int) objeto[0];
                    break;
                }
            }
        }   
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String url1 = "http://"+this.host+"/produzido/listaProduzido?produto_id="+selectedReferencia;
        var result1 = ConnectionFactory.simpleGet(url1);
        JSONArray jsonArrayProduzidos = new JSONArray(result1);
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        modelo1.setNumRows(0);
        for (int i = 0; i < jsonArrayProduzidos.length(); i++) {
            JSONObject obj = jsonArrayProduzidos.getJSONObject(i);
            modelo1.addRow(new Object[]{
                obj.getString("referencia"),
                obj.getInt("producao_diaria"),
                obj.getString("costureiro"),
                obj.getString("dia")
               });
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        alimentaTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
